doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Products:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Application/Domain/Entities/Products/Entity'
                prefix: 'App\Application\Domain\Entities\Products\Entity'
                alias: Products
            Categories:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Application/Domain/Entities/Categories/Entity'
                prefix: 'App\Application\Domain\Entities\Categories\Entity'
                alias: Categories
            Items:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Application/Domain/Entities/Items/Entity'
                prefix: 'App\Application\Domain\Entities\Items\Entity'
                alias: Items
            ProductItems:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Application/Domain/Entities/ProductItem/Entity'
                prefix: 'App\Application\Domain\Entities\ProductItem\Entity'
                alias: ProductItems
            OrderItem:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Application/Domain/Entities/Orders/Entity'
                prefix: 'App\Application\Domain\Entities\Orders\Entity'
                alias: OrderItems

        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            mappings:
                Products:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Domain/Products/Entity'
                    prefix: 'App\Domain\Products\Entity'
                    alias: Products

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
