version: "3.9"

services:
  app:
    build:
      context: ./docker/php
    container_name: producao_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/producao?serverVersion=16&charset=utf8"
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: producao_web
    depends_on:
      - app
    ports:
      - "8084:80"
    volumes:
      - ./app/public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:16
    container_name: producao_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: producao
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
