version: "3.9"

services:
  app:
    build:
      context: ./docker/php
    container_name: producao_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/producao?serverVersion=16&charset=utf8"
      MESSENGER_TRANSPORT_DSN: "amqp://symfony:symfony@rabbit:5672/%2f/messages"
    depends_on:
      - db
      - rabbit

  web:
    image: nginx:1.27-alpine
    container_name: producao_web
    depends_on:
      - app
    ports:
      - "8084:80"
    volumes:
      - ./app/public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:16
    container_name: producao_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: producao
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.13-management
    container_name: producao_rabbit
    environment:
      RABBITMQ_DEFAULT_USER: symfony
      RABBITMQ_DEFAULT_PASS: symfony
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  worker:
    build:
      context: ./docker/php
    container_name: producao_worker
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/producao?serverVersion=16&charset=utf8"
      MESSENGER_TRANSPORT_DSN: "amqp://symfony:symfony@rabbit:5672/%2f/messages"
    depends_on:
      - app
      - rabbit
    command: >
      bash -lc "php bin/console messenger:consume async
                --time-limit=3600
                --memory-limit=256M
                --limit=0
                -vv"

volumes:
  db_data:
  rabbit_data:
