nelmio_api_doc:
    documentation:
        info:
            title: Servi√ßo de Produtos - 11soat-fast-food
            version: 1.0.0
            description: API para gerenciamento de produtos no sistema 11soat-fast-food.
    areas:
        default:
            path_patterns:
                - ^/api
